- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml
  - composer 
  
- name: Configure php-fom with apache2
  become: true
  copy: src=files/www.conf dest=/etc/php/7.0/fpm/pool.d/

- name: Restart php-fpm
  become: yes
  service: name=php7.0-fpm state=restarted

- copy:
    src: files/install.sh
    dest: /tmp/
    mode: 0777

- name: Execute Install script for Composer
  command: sh /tmp/install.sh
  command: cd /var/www/html
  command: composer install 
  
  become: yes
